/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DiemDAO;
import DAO.LopHocPhanDAO;
import DAO.MonHocDAO;
import Entities.Diem;
import Entities.LopHocPhan;
import Entities.MonHoc;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author trung98
 */
public class KetQuaHocTap extends javax.swing.JFrame {

    /**
     * Creates new form KetQuaHocTap
     */
    private DefaultTableModel model;
    private ArrayList<Diem> listDiem;
    private LopHocPhan lhp;

    public KetQuaHocTap() {
        initComponents();
        model = (DefaultTableModel) bangkqht.getModel();
    }

    public void loadKetquahoctap() {
        model.setRowCount(0);
        listDiem = new DiemDAO().findByMaSV(Main.nameLogin, cb_hockykqht.getSelectedItem().toString(), cb_namhockqht.getSelectedItem().toString());
        int i = 0;
        for (Diem d : listDiem) {
            i++;
            model.addRow(toObjectsData(d, i)); // Thêm vào 1 dòng cuối cùng trong bảng Kết quả học tập 
        }
        bangkqht.setModel(model);

        float result = new DiemDAO().calDiemTB(Main.nameLogin, cb_hockykqht.getSelectedItem().toString(), cb_namhockqht.getSelectedItem().toString());
        String str = Float.toString(result);
        txtdiemtb.setText(str);

    }

    public Object[] toObjectsData(Diem d, int i) {

        lhp = new LopHocPhanDAO().findByMaLHP(d.getMaLHP(), d.getHocky(), d.getNamhoc());

        MonHoc mh = new MonHocDAO().findByMaMH(lhp.getMaMH());

        Object[] objectsData = {i, mh.getTenMH(), d.getDiemQT(), d.getDiemGK(), d.getDiemCK(), d.getDiemTB()};

        return objectsData;

    }

    private static XSSFCellStyle createStyleForTitle(XSSFWorkbook workbook) {
        XSSFFont font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        
        XSSFCellStyle style = workbook.createCellStyle();
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setFont(font);
        return style;
    }

    private static XSSFCellStyle createStyleForBold(XSSFWorkbook workbook) {
        XSSFFont font = workbook.createFont();
        font.setBold(true);

        XSSFCellStyle style = workbook.createCellStyle();
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setAlignment(HorizontalAlignment.LEFT);
        style.setFont(font);
        return style;
    }

    private static XSSFCellStyle createStyleForData(XSSFWorkbook workbook) {
        XSSFFont font = workbook.createFont();
        XSSFCellStyle style = workbook.createCellStyle();
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setAlignment(HorizontalAlignment.LEFT);
        style.setFont(font);
        return style;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_hockykqht = new javax.swing.JComboBox<>();
        cb_namhockqht = new javax.swing.JComboBox<>();
        btn_xemkqht = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bangkqht = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtdiemtb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel16.setBackground(java.awt.SystemColor.textHighlight);
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setPreferredSize(new java.awt.Dimension(976, 113));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setText("Học kỳ");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("Năm học");

        cb_hockykqht.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cb_hockykqht.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học kỳ 1", "Học kỳ 2", "Học kỳ 3" }));

        cb_namhockqht.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cb_namhockqht.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016-2017", "2017-2018", "2018-2019" }));
        cb_namhockqht.setToolTipText("");

        btn_xemkqht.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_xemkqht.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ssss.png"))); // NOI18N
        btn_xemkqht.setText("Xem");
        btn_xemkqht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemkqhtActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excel.png"))); // NOI18N
        btnExport.setText("Xuất kết quả ");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hockykqht, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(cb_namhockqht, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(btn_xemkqht)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_hockykqht)
                            .addComponent(cb_namhockqht, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_xemkqht, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bangkqht.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bangkqht.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bangkqht.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Số TT", "Môn", "Điểm quá trình", "Điểm giữa kỳ", "Điểm cuối kỳ", "Điểm trung bình"
            }
        ));
        bangkqht.setPreferredSize(new java.awt.Dimension(450, 240));
        jScrollPane4.setViewportView(bangkqht);
        bangkqht.getColumnModel().getColumn(0).setPreferredWidth(50);
        bangkqht.getColumnModel().getColumn(1).setPreferredWidth(200);
        bangkqht.getColumnModel().getColumn(2).setPreferredWidth(100);
        bangkqht.getColumnModel().getColumn(3).setPreferredWidth(100);
        bangkqht.getColumnModel().getColumn(4).setPreferredWidth(100);
        bangkqht.getColumnModel().getColumn(5).setPreferredWidth(100);

        jPanel17.setBackground(java.awt.SystemColor.textHighlight);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Điểm trung bình học kỳ :");

        txtdiemtb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(667, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemtb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xemkqhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemkqhtActionPerformed
        loadKetquahoctap();
    }//GEN-LAST:event_btn_xemkqhtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed

        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet sheet = wb.createSheet("Result");
        sheet.setColumnWidth(0, 4000);
        sheet.setColumnWidth(1, 10000);
        sheet.setColumnWidth(2, 6000);
        sheet.setColumnWidth(3, 6000);
        sheet.setColumnWidth(4, 6000);
        sheet.setColumnWidth(5, 6000);

        int rownum = 2;
        Row row;
        Cell cell;
        XSSFCellStyle style = createStyleForTitle(wb);
        XSSFCellStyle styleBold = createStyleForBold(wb);
        XSSFCellStyle styleData = createStyleForData(wb);
        row = sheet.createRow(rownum);

        
        XSSFRow title = sheet.createRow(0);
        Cell titleCell = title.createCell(2);
        String hocky=cb_hockykqht.getSelectedItem().toString().toUpperCase();
     
        titleCell.setCellValue("KẾT QUẢ HỌC TẬP " + hocky + " NĂM HỌC " + cb_namhockqht.getSelectedItem());
        
        titleCell.setCellStyle(style);

        // Số TT
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("Số TT");
        cell.setCellStyle(styleBold);
        // Môn học
        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Môn học");
        cell.setCellStyle(styleBold);
        // Điểm quá trình
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Điểm quá trình");
        cell.setCellStyle(styleBold);
        // Điểm giữa kỳ
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Điểm giữa kỳ");
        cell.setCellStyle(styleBold);
        // Điểm cuối kỳ
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("Điểm cuối kỳ");
        cell.setCellStyle(styleBold);
        // Điểm trung bình
        cell = row.createCell(5, CellType.STRING);
        cell.setCellValue("Điểm trung bình");
        cell.setCellStyle(styleBold);

        for (int i = 0; i < bangkqht.getRowCount(); i++) {
            rownum++;
            row = sheet.createRow(rownum);
            // Số TT
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue(i + 1);
            cell.setCellStyle(styleData);

            // Môn học 
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue((String) bangkqht.getValueAt(i, 1));
            cell.setCellStyle(styleData);

            // Điểm quá trình 
            cell = row.createCell(2, CellType.NUMERIC);
            cell.setCellValue(String.valueOf(bangkqht.getValueAt(i, 2)));
            cell.setCellStyle(styleData);
            // Điểm giữa kỳ 
            cell = row.createCell(3, CellType.NUMERIC);
            cell.setCellValue(String.valueOf(bangkqht.getValueAt(i, 3)));
            cell.setCellStyle(styleData);
            // Điểm cuối kỳ
            cell = row.createCell(4, CellType.NUMERIC);
            cell.setCellValue(String.valueOf(bangkqht.getValueAt(i, 4)));
            cell.setCellStyle(styleData);
            // Điểm trung bình
            cell = row.createCell(5, CellType.NUMERIC);
            cell.setCellValue(String.valueOf(bangkqht.getValueAt(i, 5)));
            cell.setCellStyle(styleData);
        }
        XSSFRow sum = sheet.createRow(10);
        Cell sumLabelCell = sum.createCell(3);
        sumLabelCell.setCellValue("Điểm trung bình học kỳ :");
        sumLabelCell.setCellStyle(styleBold);
        Cell sumCell = sum.createCell(4);
        sumCell.setCellType(CellType.FORMULA);
        sumCell.setCellFormula(txtdiemtb.getText());
        sumCell.setCellStyle(styleData);

        File file = new File("E:/Learn Java/Slide UIT/" + Main.nameLogin + ".xlsx");
        file.getParentFile().mkdirs();
        
        try {
            FileOutputStream outFile = new FileOutputStream(file);
            wb.write(outFile);
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KetQuaHocTap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(KetQuaHocTap.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KetQuaHocTap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangkqht;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btn_xemkqht;
    private javax.swing.JComboBox<String> cb_hockykqht;
    private javax.swing.JComboBox<String> cb_namhockqht;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel txtdiemtb;
    // End of variables declaration//GEN-END:variables
}
