/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB_Connect.DBConnect;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Võ Đại Nhật Trung
 */
public class Main extends javax.swing.JFrame {

    PreparedStatement ps = null;
    ResultSet rs = null;

    public static String nameLogin = "";
    public static String nameLogin2 = "";
    public static String nameLogin3 = "";

    public Main() {
        initComponents();
        tf_usersv.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        tf_usersv = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_passsv = new javax.swing.JPasswordField();
        btn_dangnhapsv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tf_usercb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_passcb = new javax.swing.JPasswordField();
        btn_dangnhapcb = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tf_userql = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_passql = new javax.swing.JPasswordField();
        btn_dangnhapql = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);

        jPanel1.setForeground(java.awt.SystemColor.textHighlight);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/uit.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRƯỜNG ĐẠI HOC CÔNG NGHỆ THÔNG TIN ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUẢN LÝ ĐÀO TẠO - UIT");

        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/placeholder.png"))); // NOI18N
        jLabel4.setText("Địa chỉ : Khu phố 6 , P.Linh Trung ,Q.Thủ Đức,Tp Hồ Chí Minh");
        jLabel4.setToolTipText("");

        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/telephone.png"))); // NOI18N
        jLabel5.setText("Điện thoại :(028) 372 52148");

        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fax.png"))); // NOI18N
        jLabel6.setText(" FAX:(028) 372 52148");

        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/email.png"))); // NOI18N
        jLabel7.setText("Email: info@uit.edu.vn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf_usersv.setText("SV");
        tf_usersv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usersvActionPerformed(evt);
            }
        });
        tf_usersv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usersvKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Mã số sinh viên");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setText("Mật khẩu");

        tf_passsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passsvActionPerformed(evt);
            }
        });
        tf_passsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_passsvKeyReleased(evt);
            }
        });

        btn_dangnhapsv.setText("Đăng nhập");
        btn_dangnhapsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapsvActionPerformed(evt);
            }
        });
        btn_dangnhapsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_dangnhapsvKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_usersv, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_passsv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dangnhapsv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usersv, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tf_passsv))
                .addGap(29, 29, 29)
                .addComponent(btn_dangnhapsv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sinh viên", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Mã số cán bộ");

        tf_usercb.setText("GV");
        tf_usercb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usercbKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Mật khẩu");

        tf_passcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passcbActionPerformed(evt);
            }
        });
        tf_passcb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_passcbKeyReleased(evt);
            }
        });

        btn_dangnhapcb.setText("Đăng nhập");
        btn_dangnhapcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dangnhapcbMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dangnhapcbMouseReleased(evt);
            }
        });
        btn_dangnhapcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapcbActionPerformed(evt);
            }
        });
        btn_dangnhapcb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_dangnhapcbKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_usercb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_passcb, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dangnhapcb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usercb, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tf_passcb))
                .addGap(35, 35, 35)
                .addComponent(btn_dangnhapcb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cán bộ", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Tên đăng nhập");

        tf_userql.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_userqlKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("Mật khẩu");

        tf_passql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passqlActionPerformed(evt);
            }
        });
        tf_passql.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_passqlKeyReleased(evt);
            }
        });

        btn_dangnhapql.setText("Đăng nhập");
        btn_dangnhapql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapqlActionPerformed(evt);
            }
        });
        btn_dangnhapql.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_dangnhapqlKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_userql, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_passql, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(btn_dangnhapql, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_userql, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tf_passql))
                .addGap(35, 35, 35)
                .addComponent(btn_dangnhapql, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_passcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passcbActionPerformed

    }//GEN-LAST:event_tf_passcbActionPerformed

    private void tf_passqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passqlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passqlActionPerformed

    private void tf_passsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passsvActionPerformed

    private void btn_dangnhapsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapsvActionPerformed
        loginSV();

    }//GEN-LAST:event_btn_dangnhapsvActionPerformed

    private void btn_dangnhapcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapcbActionPerformed
        loginGV();
    }//GEN-LAST:event_btn_dangnhapcbActionPerformed

    private void btn_dangnhapqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapqlActionPerformed
        loginAdmin();
    }//GEN-LAST:event_btn_dangnhapqlActionPerformed

    private void tf_usersvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usersvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usersvActionPerformed

    private void btn_dangnhapsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_dangnhapsvKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginSV();
        }
    }//GEN-LAST:event_btn_dangnhapsvKeyReleased

    private void tf_passsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_passsvKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginSV();
        }
    }//GEN-LAST:event_tf_passsvKeyReleased

    private void tf_usersvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usersvKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tf_passsv.requestFocus();
        }
    }//GEN-LAST:event_tf_usersvKeyReleased

    private void btn_dangnhapcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangnhapcbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangnhapcbMouseClicked

    private void btn_dangnhapcbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangnhapcbMouseReleased

    }//GEN-LAST:event_btn_dangnhapcbMouseReleased

    private void btn_dangnhapcbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_dangnhapcbKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginGV();
        }
    }//GEN-LAST:event_btn_dangnhapcbKeyReleased

    private void tf_passcbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_passcbKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginGV();
        }
    }//GEN-LAST:event_tf_passcbKeyReleased

    private void tf_passqlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_passqlKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginAdmin();
        }
    }//GEN-LAST:event_tf_passqlKeyReleased

    private void btn_dangnhapqlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_dangnhapqlKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            loginAdmin();
        }
    }//GEN-LAST:event_btn_dangnhapqlKeyReleased

    private void tf_userqlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_userqlKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tf_passql.requestFocus();
        }
    }//GEN-LAST:event_tf_userqlKeyReleased

    private void tf_usercbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usercbKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tf_passcb.requestFocus();
        }
    }//GEN-LAST:event_tf_usercbKeyReleased

    public void resetForm() {
        tf_usersv.setText("SV");
        tf_passsv.setText("");
        tf_usersv.requestFocus();
    }

    public void loginSV() {
        String str = "";
        String usersv = tf_usersv.getText();
        String passsv = tf_passsv.getText();
        if (usersv.equals(str) || passsv.equals(str)) {
            JOptionPane.showMessageDialog(null, "Tài khoản hay mật khẩu không được bỏ trúng", "Thông báo ", JOptionPane.ERROR_MESSAGE);
            this.resetForm();
        } else if (DBConnect.open()) {
            try {
                ps = DBConnect.con.prepareStatement("SELECT MASV,MATKHAU FROM SINHVIEN");
                rs = ps.executeQuery();
                while (rs.next()) {
                    if (usersv.equals(rs.getString(1)) && passsv.equals(rs.getString(2))) {
                        nameLogin = usersv;
                        break;
                    }
                }
                DBConnect.close();
                if (nameLogin != "") {
                    new MainSV().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Tên người dùng hoặc mật khẩu không hợp lệ\nXin vui lòng thử lại!", "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                    resetForm();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void loginGV() {
        String str = "";
        String usercb = tf_usercb.getText();
        String passcb = tf_passcb.getText();
        if (usercb.equals(str) || passcb.equals(str)) {
            JOptionPane.showMessageDialog(null, "Tài khoản hay mật khẩu không được bỏ trúng", "Thông báo ", JOptionPane.ERROR_MESSAGE);
            this.resetForm();
        } else if (DBConnect.open()) {
            try {
                ps = DBConnect.con.prepareStatement("SELECT MAGV,MATKHAU FROM GIAOVIEN");
                rs = ps.executeQuery();
                while (rs.next()) {
                    if (usercb.equals(rs.getString(1)) && passcb.equals(rs.getString(2))) {
                        nameLogin2 = usercb;
                        break;
                    }
                }
                DBConnect.close();
                if (nameLogin2 != "") {
                    new MainGV().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Tên người dùng hoặc mật khẩu không hợp lệ\nXin vui lòng thử lại!", "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                    resetForm();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void loginAdmin() {
        String str = "";
        String userql = tf_userql.getText();
        String passql = tf_passql.getText();
        if (userql.equals(str) || passql.equals(str)) {
            JOptionPane.showMessageDialog(null, "Tài khoản hay mật khẩu không được bỏ trúng", "Thông báo ", JOptionPane.ERROR_MESSAGE);
            this.resetForm();
        } else if (DBConnect.open()) {
            try {
                ps = DBConnect.con.prepareStatement("SELECT users,passwords FROM MANAGER");
                rs = ps.executeQuery();
                while (rs.next()) {
                    if (userql.equals(rs.getString(1)) && passql.equals(rs.getString(2))) {
                        nameLogin3 = userql;
                        break;
                    }
                }
                DBConnect.close();
                if (nameLogin3 != "") {
                    new MainQTV().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Tên người dùng hoặc mật khẩu không hợp lệ\nXin vui lòng thử lại!", "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                    resetForm();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhapcb;
    private javax.swing.JButton btn_dangnhapql;
    private javax.swing.JButton btn_dangnhapsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField tf_passcb;
    private javax.swing.JPasswordField tf_passql;
    private javax.swing.JPasswordField tf_passsv;
    private javax.swing.JTextField tf_usercb;
    private javax.swing.JTextField tf_userql;
    private javax.swing.JTextField tf_usersv;
    // End of variables declaration//GEN-END:variables
}
