/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DiemDAO;
import DAO.LopHocPhanDAO;
import DAO.MonHocDAO;
import DAO.SinhVienDAO;
import Entities.Diem;
import Entities.LopHocPhan;
import Entities.MonHoc;
import Entities.SinhVien;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trung98
 */
public class QLDiem extends javax.swing.JFrame {

    /**
     * Creates new form QLDiem
     */
    private DefaultTableModel model;

    private DefaultComboBoxModel dcbmMaMH;
    private DefaultComboBoxModel dcbmTenMH;
    private DefaultComboBoxModel dcbmLHP;
    private DefaultComboBoxModel dcbmMaSV;
    private DefaultComboBoxModel dcbmTenSV;
    private ArrayList<SinhVien> listSV;
    private ArrayList<MonHoc> listMH;
    private ArrayList<LopHocPhan> listLHP;
    private ArrayList<Diem> listDiem;

    public QLDiem() {
        initComponents();
        model = (DefaultTableModel) bangdiemsv.getModel();
        dcbmMaMH = new DefaultComboBoxModel();
        dcbmTenMH = new DefaultComboBoxModel();
        dcbmLHP = new DefaultComboBoxModel();
        dcbmMaSV = new DefaultComboBoxModel();
        dcbmTenSV = new DefaultComboBoxModel();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbmamh = new javax.swing.JComboBox<>();
        cbtenmh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cblhp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtsumrow = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        txtfind = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangdiemsv = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cbmasv = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        txtdiemqt = new javax.swing.JTextField();
        txtdiemgk = new javax.swing.JTextField();
        txtdiemck = new javax.swing.JTextField();
        txtdiemtb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH ĐIỂM LỚP HỌC PHẦN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(471, 471, 471))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbmamh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmamhItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Mã MH");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Tên MH");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Lớp");

        cblhp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cblhpItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Sinh viên");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Tổng số :");

        txtsumrow.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtsumrow.setText("0");

        btnTimkiem.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ssss.png"))); // NOI18N
        btnTimkiem.setText("Tìm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtfind.setText("Họ tên hoặc MSSV");
        txtfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfindMouseClicked(evt);
            }
        });
        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbtenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbmamh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cblhp, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnTimkiem)))
                .addGap(314, 314, 314)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsumrow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsumrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbmamh, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbtenmh)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cblhp)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bangdiemsv.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bangdiemsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SV", "Họ Tên", "Điểm QT", "Điểm GK", "Điểm CK", "Điểm TB"
            }
        ));
        bangdiemsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangdiemsvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangdiemsv);
        bangdiemsv.getColumnModel().getColumn(0).setPreferredWidth(50);
        bangdiemsv.getColumnModel().getColumn(1).setPreferredWidth(100);
        bangdiemsv.getColumnModel().getColumn(2).setPreferredWidth(200);
        bangdiemsv.getColumnModel().getColumn(3).setPreferredWidth(100);
        bangdiemsv.getColumnModel().getColumn(4).setPreferredWidth(100);
        bangdiemsv.getColumnModel().getColumn(5).setPreferredWidth(100);
        bangdiemsv.getColumnModel().getColumn(6).setPreferredWidth(100);

        jPanel4.setBackground(java.awt.SystemColor.textHighlight);
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Mã sinh viên");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Điểm quá trình");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Điểm giữa kỳ ");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Điểm cuối kỳ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Điểm trung bình ");

        btnsave.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/savev.png"))); // NOI18N
        btnsave.setText("Save ");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        txtdiemqt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdiemqtMouseClicked(evt);
            }
        });

        txtdiemgk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdiemgkMouseClicked(evt);
            }
        });

        txtdiemck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdiemckMouseClicked(evt);
            }
        });
        txtdiemck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiemckActionPerformed(evt);
            }
        });

        txtdiemtb.setEnabled(false);
        txtdiemtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdiemtbMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdiemqt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemgk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemck, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(111, 111, 111))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemqt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemgk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemck, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdiemckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiemckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiemckActionPerformed

    private void cbmamhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmamhItemStateChanged
        MonHoc mh = new MonHocDAO().findByMaMH(cbmamh.getSelectedItem().toString());

        cbtenmh.setSelectedItem(mh.getTenMH());
        listLHP = new LopHocPhanDAO().findByMaGV_DK(Main.nameLogin2, mh.getMaMH(), MainGV.hocky, MainGV.namhoc);
        dcbmLHP.removeAllElements();
        for (LopHocPhan lhp : listLHP) {
            dcbmLHP.addElement(lhp.getMaLHP());
        }
        cblhp.setModel(dcbmLHP);
    }//GEN-LAST:event_cbmamhItemStateChanged

    private void cblhpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cblhpItemStateChanged
        /* listSV = new SinhVienDAO().findByMaLHP(cblhp.getSelectedItem().toString(), MainGV.hocky, MainGV.namhoc);
        
        for (SinhVien sv : listSV) {
            dcbmTenSV.addElement(sv.getHoTen());
        
        cbsinhvien.setModel(dcbmTenSV);*/
    }//GEN-LAST:event_cblhpItemStateChanged

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        loadDataDiem();
        listSV = new SinhVienDAO().findSVByLHP(cblhp.getSelectedItem().toString(), MainGV.hocky, MainGV.namhoc);
        // dcbmTenSV.removeAllElements();
        for (SinhVien sv : listSV) {
            //dcbmTenSV.addElement(sv.getHoTen());
            dcbmMaSV.addElement(sv.getMaSV());
        }
        // cbsinhvien.setModel(dcbmTenSV);
        cbmasv.setModel(dcbmMaSV);
        //lbsumsv.setText(Integer.toString(bangdiemsv.getRowCount()));
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void bangdiemsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangdiemsvMouseClicked

        txtdiemqt.setText(String.valueOf(bangdiemsv.getValueAt(bangdiemsv.getSelectedRow(), 3)));
        txtdiemgk.setText(String.valueOf(bangdiemsv.getValueAt(bangdiemsv.getSelectedRow(), 4)));
        txtdiemck.setText(String.valueOf(bangdiemsv.getValueAt(bangdiemsv.getSelectedRow(), 5)));
        txtdiemtb.setText(String.valueOf(bangdiemsv.getValueAt(bangdiemsv.getSelectedRow(), 6)));

        cbmasv.setSelectedItem(bangdiemsv.getValueAt(bangdiemsv.getSelectedRow(), 1));


    }//GEN-LAST:event_bangdiemsvMouseClicked

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        float diemqt = Float.parseFloat(txtdiemqt.getText());
        float diemgk = Float.parseFloat(txtdiemgk.getText());
        float diemck = Float.parseFloat(txtdiemck.getText());
        String masv = cbmasv.getSelectedItem().toString();
        String malhp = cblhp.getSelectedItem().toString();
        String hocky = MainGV.hocky;
        String namhoc = MainGV.namhoc;

        Diem d = new Diem(masv, malhp, hocky, namhoc, diemqt, diemgk, diemck);

        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn lưu thay đổi ", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            boolean update = new DiemDAO().updateDiem(d);
            if (update) {
                JOptionPane.showMessageDialog(this, "Cập nhật điểm thành công ", "Thông báo ", JOptionPane.INFORMATION_MESSAGE);
                loadDataDiem();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại ", "Thông báo ", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdiemqtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiemqtMouseClicked
        txtdiemqt.setText("");
    }//GEN-LAST:event_txtdiemqtMouseClicked

    private void txtdiemgkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiemgkMouseClicked
        txtdiemgk.setText("");
    }//GEN-LAST:event_txtdiemgkMouseClicked

    private void txtdiemckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiemckMouseClicked
        txtdiemck.setText("");
    }//GEN-LAST:event_txtdiemckMouseClicked

    private void txtdiemtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiemtbMouseClicked

    }//GEN-LAST:event_txtdiemtbMouseClicked

    private void txtfindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindMouseClicked
        txtfind.setText("");
    }//GEN-LAST:event_txtfindMouseClicked

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        findSV();
        setTongso();
    }//GEN-LAST:event_txtfindKeyPressed

    /**
     * @param args the command line arguments
     */
    public DefaultComboBoxModel chooseModel() {

        DefaultComboBoxModel dcbm = null;
        return dcbm;

    }

    public void findSV() {
        listSV = new SinhVienDAO().findSVByName(txtfind.getText());
        int i = 1;
        model.setRowCount(0);
        for (SinhVien sv : listSV) {
            model.addRow(toObjectsDataSV(sv, i));
            i++;
        }
        bangdiemsv.setModel(model);

    }

    public void loadDataDiem() {
        model.setRowCount(0);
        listSV = new SinhVienDAO().findSVByLHP(cblhp.getSelectedItem().toString(), MainGV.hocky, MainGV.namhoc);
        int i = 1;
        for (SinhVien sv : listSV) {
            model.addRow(toObjectsDataSV(sv, i));
            i++;
        }
        bangdiemsv.setModel(model);
        setTongso();
    }

    public void setTongso() {

        txtsumrow.setText(Integer.toString(bangdiemsv.getRowCount()));
    }

    public void loadComboBox() {
        listMH = new MonHocDAO().findByMaGV_DK(Main.nameLogin2, MainGV.hocky, MainGV.namhoc);
        for (MonHoc mh : listMH) {
            dcbmMaMH.addElement(mh.getMaMH());
            dcbmTenMH.addElement(mh.getTenMH());

        }
        cbmamh.setModel(dcbmMaMH);
        cbtenmh.setModel(dcbmTenMH);

        listLHP = new LopHocPhanDAO().findByMaGV_DK(Main.nameLogin2, cbmamh.getSelectedItem().toString(), MainGV.hocky, MainGV.namhoc);
        dcbmLHP.removeAllElements();
        for (LopHocPhan lhp : listLHP) {
            dcbmLHP.addElement(lhp.getMaLHP());
        }
        cblhp.setModel(dcbmLHP);

    }

    public Object[] toObjectsDataSV(SinhVien sv, int i) {

        Diem diem = new DiemDAO().findDiemSV_LHP(sv.getMaSV(), cblhp.getSelectedItem().toString(), MainGV.hocky, MainGV.namhoc);
        Object[] ob = {i, sv.getMaSV(), sv.getHoTen(), diem.getDiemQT(), diem.getDiemGK(), diem.getDiemCK(), diem.getDiemTB()};
        return ob;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangdiemsv;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cblhp;
    private javax.swing.JComboBox<String> cbmamh;
    private javax.swing.JComboBox<String> cbmasv;
    private javax.swing.JComboBox<String> cbtenmh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdiemck;
    private javax.swing.JTextField txtdiemgk;
    private javax.swing.JTextField txtdiemqt;
    private javax.swing.JTextField txtdiemtb;
    private javax.swing.JTextField txtfind;
    private javax.swing.JLabel txtsumrow;
    // End of variables declaration//GEN-END:variables
}
