/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Check.Check;
import DAO.GiaoVienDAO;
import DAO.KhoaDAO;
import Date.DayNow;
import Entities.Khoa;
import java.awt.JobAttributes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trung98
 */
public class QLKhoa extends javax.swing.JFrame {

    /**
     * Creates new form QLKhoa
     */
    private DefaultTableModel model;
    private ArrayList<Khoa> listKhoa;

    public QLKhoa() {
        initComponents();
        model = (DefaultTableModel) bangdsk.getModel();
        loadQLK();

    }

    public void loadQLK() {
        model.setRowCount(0);
        listKhoa = new KhoaDAO().getAll();
        int i = 1;
        for (Khoa k : listKhoa) {
            int count = new GiaoVienDAO().countGVByKhoa(k.getMakhoa());
            model.addRow(new Object[]{i, k.getMakhoa(), k.getTenkhoa(), k.getNgtl(), k.getTrgkhoa(), count});
            i++;
        }
        bangdsk.setModel(model);

    }

    public boolean checkinfoKhoa() {
        Check c = new Check();

        if (!c.checkMakhoa(txtmakhoa.getText())) {
            JOptionPane.showMessageDialog(this, "Mã khoa không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtmakhoa.setText("GV");
            txtmakhoa.requestFocus();
            return false;
        } /*else if (!c.checkTenkhoa(txttenkhoa.getText())) {
            JOptionPane.showMessageDialog(this, "Tên khoa không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txttenkhoa.setText("");
            txttenkhoa.requestFocus();
            return false;
        }*/ else if (!c.checkNgthlap(dcngtl.getDate())) {
            JOptionPane.showMessageDialog(this, "Ngày thành lập phải nhỏ hơn hoặc bằng ngày hiện tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            dcngtl.requestFocus();
            return false;
        }/* else if (!c.checkHoten(txttrgkhoa.getText())) {
            JOptionPane.showMessageDialog(this, "Họ tên trưởng khoa không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txttrgkhoa.setText("");
            txttrgkhoa.requestFocus();
            return false;
        }*/
        return true;
    }

    private void resetFormQlk() {

        txtmakhoa.setText("");
        dcngtl.setDate(null);
        txttenkhoa.setText("");
        txttrgkhoa.setText("");

        txtmakhoa.setEnabled(true);
        btnThemKhoa.setEnabled(true);
        btnSuaKhoa.setEnabled(false);
        btnXoaKhoa.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        btnThemKhoa = new javax.swing.JButton();
        btnSuaKhoa = new javax.swing.JButton();
        btnXoaKhoa = new javax.swing.JButton();
        btnLammoiKhoa = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        bangdsk = new javax.swing.JTable();
        jPanel28 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        txtmakhoa = new javax.swing.JTextField();
        txttenkhoa = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        txttrgkhoa = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        dcngtl = new com.toedter.calendar.JDateChooser();
        jPanel32 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField19 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý khoa");

        jPanel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel103.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel103.setText("DANH SÁCH KHOA");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addComponent(jLabel103)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemKhoa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnThemKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insert_1.png"))); // NOI18N
        btnThemKhoa.setText("Insert ");
        btnThemKhoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhoaActionPerformed(evt);
            }
        });

        btnSuaKhoa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSuaKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update_1.png"))); // NOI18N
        btnSuaKhoa.setText("Update");
        btnSuaKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKhoaActionPerformed(evt);
            }
        });

        btnXoaKhoa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnXoaKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_1.png"))); // NOI18N
        btnXoaKhoa.setText("Delete");
        btnXoaKhoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhoaActionPerformed(evt);
            }
        });

        btnLammoiKhoa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLammoiKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refresh-button (1).png"))); // NOI18N
        btnLammoiKhoa.setText("Refresh ");
        btnLammoiKhoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLammoiKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiKhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnThemKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLammoiKhoa)
                .addGap(36, 36, 36))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        bangdsk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bangdsk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã khoa", "Tên khoa", "Ngày thành lập", "Trưởng khoa", "Số giáo viên"
            }
        ));
        bangdsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangdskMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(bangdsk);
        bangdsk.getColumnModel().getColumn(0).setPreferredWidth(50);
        bangdsk.getColumnModel().getColumn(1).setPreferredWidth(100);
        bangdsk.getColumnModel().getColumn(2).setPreferredWidth(200);
        bangdsk.getColumnModel().getColumn(3).setPreferredWidth(100);
        bangdsk.getColumnModel().getColumn(4).setPreferredWidth(150);
        bangdsk.getColumnModel().getColumn(5).setPreferredWidth(100);

        jPanel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel76.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel76.setText("Mã khoa");

        jLabel84.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel84.setText("Tên khoa");

        jLabel87.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel87.setText("* Thông tin chi tiết");

        jLabel85.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel85.setText("Trưởng khoa");

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel68.setText("Ngày thành lập");

        dcngtl.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttenkhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtmakhoa))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttrgkhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcngtl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcngtl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttrgkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel32.setBackground(java.awt.SystemColor.textHighlight);
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel73.setText("* Tìm kiếm");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ssss.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Tìm khoa");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhoaActionPerformed
        if (!checkinfoKhoa()) {
            return;
        }
        String makhoa = txtmakhoa.getText();
        String tenkhoa = txttenkhoa.getText();
        String ngtl = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngtl.getDate()));
        String trgkhoa = txttrgkhoa.getText();

        Khoa khoa = new Khoa(makhoa, tenkhoa, ngtl, trgkhoa);
        boolean checkID = new KhoaDAO().checkMakhoa(makhoa);
        if (!checkID) {
            JOptionPane.showMessageDialog(this, "Mã khoa đã tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            boolean insert = new KhoaDAO().themKhoa(khoa);
            if (insert) {
                JOptionPane.showMessageDialog(this, "Thêm khoa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetFormQlk();
                loadQLK();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm khoa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetFormQlk();
            }
        }
    }//GEN-LAST:event_btnThemKhoaActionPerformed

    private void btnSuaKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKhoaActionPerformed
        if (!checkinfoKhoa()) {
            return;
        }
        String makhoa = txtmakhoa.getText();
        String tenkhoa = txttenkhoa.getText();
        String ngtl = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngtl.getDate()));
        String trgkhoa = txttrgkhoa.getText();
        Khoa khoa = new Khoa(makhoa, tenkhoa, ngtl, trgkhoa);
        boolean update = new KhoaDAO().suaKhoa(khoa);
        if (update) {
            JOptionPane.showMessageDialog(this, "Cập nhật khoa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            resetFormQlk();
            loadQLK();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật khoa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            resetFormQlk();
        }
    }//GEN-LAST:event_btnSuaKhoaActionPerformed

    private void btnXoaKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoaActionPerformed
        String makhoa = txtmakhoa.getText();
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa khoa này không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            boolean delete = new KhoaDAO().xoaKhoa(makhoa);
            if (delete) {
                JOptionPane.showMessageDialog(this, "Xóa khoa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetFormQlk();
                loadQLK();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa khoa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetFormQlk();
            }
        }

    }//GEN-LAST:event_btnXoaKhoaActionPerformed

    private void btnLammoiKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiKhoaActionPerformed
        resetFormQlk();
    }//GEN-LAST:event_btnLammoiKhoaActionPerformed

    private void bangdskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangdskMouseClicked
        txtmakhoa.setText((String) bangdsk.getValueAt(bangdsk.getSelectedRow(), 1));
        txttenkhoa.setText((String) bangdsk.getValueAt(bangdsk.getSelectedRow(), 2));
        txttrgkhoa.setText((String) bangdsk.getValueAt(bangdsk.getSelectedRow(), 4));

        String ngtl = (String) bangdsk.getValueAt(bangdsk.getSelectedRow(), 3);

        dcngtl.setDate(new DayNow().converttoDate(ngtl));

        txtmakhoa.setEnabled(false);
        btnThemKhoa.setEnabled(false);
        btnSuaKhoa.setEnabled(true);
        btnXoaKhoa.setEnabled(true);
    }//GEN-LAST:event_bangdskMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangdsk;
    private javax.swing.JButton btnLammoiKhoa;
    private javax.swing.JButton btnSuaKhoa;
    private javax.swing.JButton btnThemKhoa;
    private javax.swing.JButton btnXoaKhoa;
    private com.toedter.calendar.JDateChooser dcngtl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField txtmakhoa;
    private javax.swing.JTextField txttenkhoa;
    private javax.swing.JTextField txttrgkhoa;
    // End of variables declaration//GEN-END:variables
}
