/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Check.Check;
import DAO.DangKyHocDAO;
import DAO.GiaoVienDAO;
import DAO.LichThiDAO;
import DAO.LopHocPhanDAO;
import DAO.MonHocDAO;
import Date.DayNow;
import Entities.GiaoVien;
import Entities.LichThi;
import Entities.LopHocPhan;
import Entities.MonHoc;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trung98
 */
public class QLLopHocPhan extends javax.swing.JFrame {

    /**
     * Creates new form QLLopHocPhan
     */
    private DefaultTableModel model;
    private ArrayList<LopHocPhan> listLHP;
    private ArrayList<MonHoc> listMH;
    private ArrayList<GiaoVien> listGV;
    private DefaultComboBoxModel dcbmMaMH;
    private DefaultComboBoxModel dcbmTenMH;
    private DefaultComboBoxModel dcbmMaGV;

    public QLLopHocPhan() {
        initComponents();
        model = (DefaultTableModel) bangdslhp.getModel();
        dcbmMaMH = new DefaultComboBoxModel();
        dcbmTenMH = new DefaultComboBoxModel();
        dcbmMaGV = new DefaultComboBoxModel();
        loadData();
        resetFormQllhp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadData() {

        // đổ dữ liệu vào CB MaxMH,TeenMH từ CSDL
        listMH = new MonHocDAO().getAll();
        for (MonHoc mh : listMH) {
            dcbmMaMH.addElement(mh.getMaMH());
            dcbmTenMH.addElement(mh.getTenMH());
        }
        cbmamh.setModel(dcbmMaMH);
        cbtenmh.setModel(dcbmTenMH);

        // đổ dữ liệu vào CB Mã giáo viên từ CSDL
        listGV = new GiaoVienDAO().getAll();
        dcbmMaGV.removeAllElements();
        dcbmMaGV.addElement("");
        for (GiaoVien gv : listGV) {
            dcbmMaGV.addElement(gv.getMaGV());
        }
        cbmagv.setModel(dcbmMaGV);

    }

    public Object[] toObjectsDataLHP(LopHocPhan lhp) {

        MonHoc mh = new MonHocDAO().findByMaMH(lhp.getMaMH());

        Object[] ob = {lhp.getMaLHP(), lhp.getMaMH(), mh.getTenMH(), mh.getMaKhoa(), lhp.getMaGV(), lhp.getThu(), lhp.getTiet(), lhp.getPhonghoc(),
            lhp.getSiso(), lhp.getNgayBD(), lhp.getNgayKT()};
        return ob;
    }

    public void findLHPByTenMH() {
        listLHP = new LopHocPhanDAO().findByTenMH(txtfindmh.getText(), cbhockylhp.getSelectedItem().toString(), cbnamhoclhp.getSelectedItem().toString());

        model.setRowCount(0);
        for (LopHocPhan lhp : listLHP) {
            model.addRow(toObjectsDataLHP(lhp));

        }
        bangdslhp.setModel(model);

    }

    public boolean checkinfoLHP() {

        Check c = new Check();
        listMH = new MonHocDAO().getAll();
        boolean ch = false;
        for (MonHoc mh : listMH) {
            if (txtmalhp.getText().substring(0, 5).equals(mh.getMaMH())) {
                ch = true;
                break;
            }
        }
        if (txtmalhp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã lớp học phần không được trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtmalhp.setText("");
            txtmalhp.requestFocus();
            return false;
        } else if (!ch) {
            JOptionPane.showMessageDialog(this, "Mã lớp học phần phải bắt đầu bầu mã môn học VD:(IT001.1)", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtmalhp.setText("");
            txtmalhp.requestFocus();
            return false;
        } else if (!c.checkThu(txtthu.getText())) {
            JOptionPane.showMessageDialog(this, "Thứ không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtthu.setText("");
            txtthu.requestFocus();
            return false;

        } else if (!c.checkTiet(txttiet.getText())) {
            JOptionPane.showMessageDialog(this, "Tiết không hợp lệ không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txttiet.setText("");
            txttiet.requestFocus();
            return false;

        } else if (!c.checkPhong(txtphong.getText())) {
            JOptionPane.showMessageDialog(this, "Phòng không hợp lệ không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtphong.setText("");
            txtphong.requestFocus();
            return false;

        } else if (!c.checkSiso(txtsiso.getText())) {
            JOptionPane.showMessageDialog(this, "Sỉ số không hợp lệ không hợp lệ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtsiso.setText("");
            txtsiso.requestFocus();
            return false;
        } else if (((JTextField) dcngbd.getDateEditor().getUiComponent()).getText().equals("") == true) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được bỏ trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            dcngbd.requestFocus();
            return false;
        } else if (((JTextField) dcngkt.getDateEditor().getUiComponent()).getText().equals("") == true) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không được bỏ trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            dcngkt.requestFocus();
            return false;
        } else if (!c.checkDiffTwoDays(dcngbd.getDate(), dcngkt.getDate())) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải lớn hơn ngày bắt đầu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            dcngkt.requestFocus();
            return false;
        }

        return true;

    }

    private void resetFormQllhp() {
        txtmalhp.setText("");
        txtthu.setText("");
        txttiet.setText("");
        txtphong.setText("");
        txtsiso.setText("");
        dcngbd.setDate(null);
        dcngkt.setDate(null);

        txtmalhp.setEnabled(true);
        cbmamh.setEnabled(true);
        cbtenmh.setEnabled(true);
        btnThemLHP.setEnabled(true);
        btnSuaLHP.setEnabled(false);
        btnXoaLHP.setEnabled(false);

    }

    public void loaddslhp() {
        listLHP = new LopHocPhanDAO().getAll(cbhockylhp.getSelectedItem().toString(), cbnamhoclhp.getSelectedItem().toString());
        model.setRowCount(0);
        for (LopHocPhan lhp : listLHP) {
            model.addRow(toObjectsDataLHP(lhp));
        }
        bangdslhp.setModel(model);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbhockylhp = new javax.swing.JComboBox<>();
        cbnamhoclhp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnxemlhp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfindmh = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangdslhp = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        txtmalhp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbtenmh = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cbmamh = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbnamhoc = new javax.swing.JComboBox<>();
        cbhocky = new javax.swing.JComboBox<>();
        cbmagv = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtphong = new javax.swing.JTextField();
        txttiet = new javax.swing.JTextField();
        txtthu = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtsiso = new javax.swing.JTextField();
        dcngbd = new com.toedter.calendar.JDateChooser();
        dcngkt = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        btnSuaLHP = new javax.swing.JButton();
        btnThemLHP = new javax.swing.JButton();
        btnLammoiLHP = new javax.swing.JButton();
        btnXoaLHP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý lớp học phần");

        jPanel7.setBackground(java.awt.SystemColor.textHighlight);
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbhockylhp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbhockylhp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học kỳ 1", "Học kỳ 2", "Học kỳ 3" }));

        cbnamhoclhp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbnamhoclhp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016-2017", "2017-2018", "2018-2019" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Học kỳ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Năm học");

        btnxemlhp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnxemlhp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ssss.png"))); // NOI18N
        btnxemlhp.setText("Xem");
        btnxemlhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemlhpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH LỚP HỌC PHẦN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtfindmh.setText(" Tìm môn học");
        txtfindmh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfindmhMouseClicked(evt);
            }
        });
        txtfindmh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindmhKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtfindmh, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbhockylhp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbnamhoclhp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnxemlhp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnamhoclhp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbhockylhp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxemlhp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfindmh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bangdslhp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bangdslhp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã LHP", "MãMH", "TênMH", "Mã Khoa", "MãGV", "Thứ", "Tiết ", "Phòng", "Sỉ số", "Ngày BĐ", "Ngày KT"
            }
        ));
        bangdslhp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangdslhpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangdslhp);
        bangdslhp.getColumnModel().getColumn(0).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(1).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(2).setPreferredWidth(150);
        bangdslhp.getColumnModel().getColumn(3).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(4).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(5).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(6).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(7).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(8).setPreferredWidth(50);
        bangdslhp.getColumnModel().getColumn(9).setPreferredWidth(80);
        bangdslhp.getColumnModel().getColumn(10).setPreferredWidth(80);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Mã LHP");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Tên MH");

        cbtenmh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel23.setText("Mã MH");

        cbmamh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmamhItemStateChanged(evt);
            }
        });
        cbmamh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbmamhMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbmamhMouseReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setText("Mã GV");

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel25.setText("Học kỳ");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel26.setText("Năm học");

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel27.setText("Ngày BĐ");

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel28.setText("Ngày KT");

        cbnamhoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016-2017", "2017-2018", "2018-2019" }));
        cbnamhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnamhocActionPerformed(evt);
            }
        });

        cbhocky.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học kỳ 1", "Học kỳ 2", "Học kỳ 3" }));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setText("Thứ");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setText("Tiết");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Phòng");

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel29.setText("Sĩ số");

        dcngbd.setDateFormatString("dd-MM-yyyy");

        dcngkt.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbmamh, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                        .addComponent(txtmalhp, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cbtenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbhocky, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbmagv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txttiet, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtthu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtphong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsiso)
                    .addComponent(dcngbd, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(dcngkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(txtsiso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dcngbd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dcngkt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txttiet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(txtphong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtthu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmalhp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmagv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbmamh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbhocky, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSuaLHP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSuaLHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update_1.png"))); // NOI18N
        btnSuaLHP.setText("Update");
        btnSuaLHP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSuaLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLHPActionPerformed(evt);
            }
        });

        btnThemLHP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnThemLHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insert_1.png"))); // NOI18N
        btnThemLHP.setText("Insert");
        btnThemLHP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLHPActionPerformed(evt);
            }
        });

        btnLammoiLHP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLammoiLHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refresh-button (1).png"))); // NOI18N
        btnLammoiLHP.setText("Refresh");
        btnLammoiLHP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLammoiLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiLHPActionPerformed(evt);
            }
        });

        btnXoaLHP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnXoaLHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_1.png"))); // NOI18N
        btnXoaLHP.setText("Delete");
        btnXoaLHP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLHPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLammoiLHP))
                .addGap(48, 48, 48))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLammoiLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1371, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxemlhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemlhpActionPerformed
        loaddslhp();
    }//GEN-LAST:event_btnxemlhpActionPerformed

    private void txtfindmhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindmhMouseClicked
        txtfindmh.setText("");
    }//GEN-LAST:event_txtfindmhMouseClicked

    private void txtfindmhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindmhKeyPressed
        findLHPByTenMH();
    }//GEN-LAST:event_txtfindmhKeyPressed

    private void bangdslhpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangdslhpMouseClicked

        txtmalhp.setText((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 0));
        cbmamh.setSelectedItem(bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 1));
        cbtenmh.setSelectedItem(bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 2));

        //cbmagv.setSelectedItem(bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 4));
        cbhocky.setSelectedItem((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 9));
        cbnamhoc.setSelectedItem((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 10));
        txtthu.setText((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 5));
        txttiet.setText((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 6));
        txtphong.setText((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 7));
        txtsiso.setText((String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 8));

        String ngbd = (String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 9);
        String ngkt = (String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 10);
        dcngbd.setDate(new DayNow().converttoDate(ngbd));
        dcngkt.setDate(new DayNow().converttoDate(ngkt));

        if (bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 4) == null) {
            cbmagv.setSelectedIndex(0);
        } else {
            cbmagv.setSelectedItem(bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 4));
        }

        txtmalhp.setEnabled(false);
        cbmamh.setEnabled(false);
        cbtenmh.setEnabled(false);
        btnThemLHP.setEnabled(false);
        btnSuaLHP.setEnabled(true);
        btnXoaLHP.setEnabled(true);
    }//GEN-LAST:event_bangdslhpMouseClicked

    private void cbmamhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmamhItemStateChanged
        MonHoc mh = new MonHocDAO().findByMaMH(cbmamh.getSelectedItem().toString());
        cbtenmh.setSelectedItem(mh.getTenMH());
    }//GEN-LAST:event_cbmamhItemStateChanged

    private void cbmamhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbmamhMouseClicked

    }//GEN-LAST:event_cbmamhMouseClicked

    private void cbmamhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbmamhMouseReleased

    }//GEN-LAST:event_cbmamhMouseReleased

    private void cbnamhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnamhocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnamhocActionPerformed

    private void btnSuaLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLHPActionPerformed
        if (!checkinfoLHP()) {
            return;
        }

        String malhp = txtmalhp.getText();
        String hocky = cbhockylhp.getSelectedItem().toString();
        String namhoc = cbnamhoclhp.getSelectedItem().toString();
        String mamh = cbmamh.getSelectedItem().toString();
        String thu = txtthu.getText();
        String tiet = txttiet.getText();
        String phong = txtphong.getText();
        String magv = cbmagv.getSelectedItem().toString();
        String siso = txtsiso.getText();
        String ngbd = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngbd.getDate()));
        String ngkt = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngkt.getDate()));

        LopHocPhan lhp = new LopHocPhan(malhp, mamh, thu, tiet, phong, siso, magv, ngbd, ngkt, hocky, namhoc);

        if (magv.equals("")) {
            boolean update1 = new LopHocPhanDAO().suaLHPnoGV(lhp);
            if (update1) {
                JOptionPane.showMessageDialog(this, "Cập nhật lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loaddslhp();
                resetFormQllhp();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật lớp học phần thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            boolean update2 = new LopHocPhanDAO().suaLHP(lhp);
            if (update2) {
                JOptionPane.showMessageDialog(this, "Cập nhật lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loaddslhp();
                resetFormQllhp();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật lớp học phần thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaLHPActionPerformed

    private void btnThemLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLHPActionPerformed
        if (!checkinfoLHP()) {
            return;
        }
        String malhp = txtmalhp.getText();
        String hocky = cbhocky.getSelectedItem().toString();
        String namhoc = cbnamhoc.getSelectedItem().toString();
        String mamh = cbmamh.getSelectedItem().toString();
        String thu = txtthu.getText();
        String tiet = txttiet.getText();
        String phong = txtphong.getText();
        String magv = cbmagv.getSelectedItem().toString();
        String siso = txtsiso.getText();
        String ngbd = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngbd.getDate()));
        String ngkt = new DayNow().converttoString(new DayNow().convertFromJAVADateToSQLDate(dcngkt.getDate()));
        LopHocPhan lhp = new LopHocPhan(malhp, mamh, thu, tiet, phong, siso, magv, ngbd, ngkt, hocky, namhoc);
        boolean chmalhp = new LopHocPhanDAO().checkMaLHP(malhp, hocky, namhoc);
        if (!chmalhp) {
            JOptionPane.showMessageDialog(this, "Lớp học phần này đã tồn tại\nXin vui lòng thử lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            if (magv.equals("")) {
                boolean insert = new LopHocPhanDAO().themLHPnoGV(lhp);
                if (insert) {
                    JOptionPane.showMessageDialog(this, "Thêm lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    loaddslhp();
                    resetFormQllhp();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm lớp học phần thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                boolean insert = new LopHocPhanDAO().themLHP(lhp);
                if (insert) {
                    JOptionPane.showMessageDialog(this, "Thêm lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    loaddslhp();
                    resetFormQllhp();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm lớp học phần thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnThemLHPActionPerformed

    private void btnLammoiLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiLHPActionPerformed
        resetFormQllhp();
    }//GEN-LAST:event_btnLammoiLHPActionPerformed

    private void btnXoaLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLHPActionPerformed
        String maLHP = (String) bangdslhp.getValueAt(bangdslhp.getSelectedRow(), 0);
        String hocky = cbhockylhp.getSelectedItem().toString();
        String namhoc = cbnamhoclhp.getSelectedItem().toString();

        int check = JOptionPane.showConfirmDialog(this, "Nếu bạn xóa lớp học phần này thì tất cả sinh viên đã đăng ký\n học phần này sẽ bị xóa hết"
                + "và những thứ liên quan đến lớp học phần này cũng bị hủy\nBạn có chắc chắn muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            new DangKyHocDAO().deleteByMaLHP(maLHP, hocky, namhoc);
            LichThi lt = new LichThi(maLHP, hocky, namhoc);
            new LichThiDAO().xoaLichthi(lt);
            LopHocPhan lhp = new LopHocPhan(maLHP, hocky, namhoc);
            new LopHocPhanDAO().xoaLHP(lhp);
            JOptionPane.showMessageDialog(this, "Bạn đã xóa lớp học phần thành công", "Thông báo ", JOptionPane.INFORMATION_MESSAGE);
            loaddslhp();
            resetFormQllhp();
        }
    }//GEN-LAST:event_btnXoaLHPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLopHocPhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangdslhp;
    private javax.swing.JButton btnLammoiLHP;
    private javax.swing.JButton btnSuaLHP;
    private javax.swing.JButton btnThemLHP;
    private javax.swing.JButton btnXoaLHP;
    private javax.swing.JButton btnxemlhp;
    private javax.swing.JComboBox<String> cbhocky;
    private javax.swing.JComboBox<String> cbhockylhp;
    private javax.swing.JComboBox<String> cbmagv;
    private javax.swing.JComboBox<String> cbmamh;
    private javax.swing.JComboBox<String> cbnamhoc;
    private javax.swing.JComboBox<String> cbnamhoclhp;
    private javax.swing.JComboBox<String> cbtenmh;
    private com.toedter.calendar.JDateChooser dcngbd;
    private com.toedter.calendar.JDateChooser dcngkt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtfindmh;
    private javax.swing.JTextField txtmalhp;
    private javax.swing.JTextField txtphong;
    private javax.swing.JTextField txtsiso;
    private javax.swing.JTextField txtthu;
    private javax.swing.JTextField txttiet;
    // End of variables declaration//GEN-END:variables
}
