/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DangKyHocDAO;
import DAO.DieuKienDAO;
import DAO.KhoaDAO;
import DAO.LichThiDAO;
import DAO.LopHocPhanDAO;
import DAO.MonHocDAO;
import Entities.DieuKien;
import Entities.Khoa;
import Entities.LopHocPhan;
import Entities.MonHoc;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trung98
 */
public class QLMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form QLMonHoc
     */
    private DefaultTableModel model;
    private ArrayList<Khoa> listKhoa;
    private ArrayList<MonHoc> listMH;
    private DefaultComboBoxModel dcbmMakhoa1;
    private DefaultComboBoxModel dcbmMakhoa2;
    private DefaultComboBoxModel dcbmMaMH;
    private DefaultComboBoxModel dcbmTenMH;

    public QLMonHoc() {
        initComponents();
        model = (DefaultTableModel) bangdsmh.getModel();
        dcbmMakhoa1 = new DefaultComboBoxModel();
        dcbmMakhoa2 = new DefaultComboBoxModel();
        dcbmMaMH = new DefaultComboBoxModel();
        dcbmTenMH = new DefaultComboBoxModel();
        loadComboBox();
        loadQlmh();
        resetFormQlmh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangdsmh = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtmamh = new javax.swing.JTextField();
        txttenmh = new javax.swing.JTextField();
        cbmakhoa = new javax.swing.JComboBox<>();
        txtsotc = new javax.swing.JTextField();
        cbmamhtr = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbtenmhtr = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnThemMH = new javax.swing.JButton();
        btnSuaMH = new javax.swing.JButton();
        btnXoaMH = new javax.swing.JButton();
        btnLammoiMH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý môn học");

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH CÁC MÔN HỌC");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(385, 385, 385)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bangdsmh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bangdsmh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã MH", "Tên MH", "Số TC", "Mã MH Trước", "Mã Khoa QL"
            }
        ));
        bangdsmh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangdsmhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangdsmh);
        bangdsmh.getColumnModel().getColumn(0).setPreferredWidth(50);
        bangdsmh.getColumnModel().getColumn(1).setPreferredWidth(80);
        bangdsmh.getColumnModel().getColumn(2).setPreferredWidth(200);
        bangdsmh.getColumnModel().getColumn(3).setPreferredWidth(50);
        bangdsmh.getColumnModel().getColumn(4).setPreferredWidth(100);
        bangdsmh.getColumnModel().getColumn(5).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbmamhtr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmamhtrItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Mã MH");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Tên MH");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Mã Khoa");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Số TC");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Mã MH Trước");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Tên MH Trước");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("*Thông tin chi tiết");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmamh)
                                    .addComponent(txttenmh)
                                    .addComponent(cbmakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsotc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmamhtr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbtenmhtr, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmamh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsotc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmamhtr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmakhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtenmhtr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemMH.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnThemMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insert_1.png"))); // NOI18N
        btnThemMH.setText("Insert");
        btnThemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMHActionPerformed(evt);
            }
        });

        btnSuaMH.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSuaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update_1.png"))); // NOI18N
        btnSuaMH.setText("Update");
        btnSuaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMHActionPerformed(evt);
            }
        });

        btnXoaMH.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnXoaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_1.png"))); // NOI18N
        btnXoaMH.setText("Delete");
        btnXoaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMHActionPerformed(evt);
            }
        });

        btnLammoiMH.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLammoiMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refresh-button (1).png"))); // NOI18N
        btnLammoiMH.setText("Refresh");
        btnLammoiMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaMH)
                .addGap(18, 18, 18)
                .addComponent(btnXoaMH)
                .addGap(15, 15, 15)
                .addComponent(btnLammoiMH)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoiMH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangdsmhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangdsmhMouseClicked
        txtmamh.setText((String) bangdsmh.getValueAt(bangdsmh.getSelectedRow(), 1));
        txttenmh.setText((String) bangdsmh.getValueAt(bangdsmh.getSelectedRow(), 2));
        txtsotc.setText((String) bangdsmh.getValueAt(bangdsmh.getSelectedRow(), 3));
        cbmamhtr.setSelectedItem(bangdsmh.getValueAt(bangdsmh.getSelectedRow(), 4));
        cbmakhoa.setSelectedItem((String) bangdsmh.getValueAt(bangdsmh.getSelectedRow(), 5));

        txtmamh.setEnabled(false);
        btnThemMH.setEnabled(false);
        btnSuaMH.setEnabled(true);
        btnXoaMH.setEnabled(true);
    }//GEN-LAST:event_bangdsmhMouseClicked

    private void cbmamhtrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmamhtrItemStateChanged
        if (cbmamhtr.getSelectedIndex() == 0) {
            cbtenmhtr.setSelectedIndex(0);
        } else {
            MonHoc mh = new MonHocDAO().findByMaMH((String) cbmamhtr.getSelectedItem());
            cbtenmhtr.setSelectedItem(mh.getTenMH());
        }
    }//GEN-LAST:event_cbmamhtrItemStateChanged

    private void btnThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMHActionPerformed

        String mamh = txtmamh.getText();
        String tenmh = txttenmh.getText();
        String sotc = txtsotc.getText();
        String makhoa = (String) cbmakhoa.getSelectedItem();
        String mamh_truoc = (String) cbmamhtr.getSelectedItem();

        MonHoc mh = new MonHoc(mamh, tenmh, sotc, makhoa);

        DieuKien dk = new DieuKien(mamh, mamh_truoc);
        boolean insert = new MonHocDAO().themMonhoc(mh);
        if (insert) {
            if (cbmamhtr.getSelectedIndex() != 0) {
                new DieuKienDAO().themDieuKien(dk);
            }
            JOptionPane.showMessageDialog(this, "Thêm môn học thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadQlmh();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm môn học thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnThemMHActionPerformed

    private void btnSuaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMHActionPerformed
        String mamh = txtmamh.getText();
        String tenmh = txttenmh.getText();
        String sotc = txtsotc.getText();
        String makhoa = (String) cbmakhoa.getSelectedItem();

        MonHoc mh = new MonHoc(mamh, tenmh, sotc, makhoa);
        boolean update = new MonHocDAO().suaMonhoc(mh);

        if (update) {
            if (cbmamhtr.getSelectedIndex() != 0) {
                String mamh_truoc = cbmamhtr.getSelectedItem().toString();
                DieuKien dk = new DieuKien(mamh, mamh_truoc);
                new DieuKienDAO().themDieuKien(dk);
            }
            JOptionPane.showMessageDialog(this, "Sửa môn học thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadQlmh();
            resetFormQlmh();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa môn học thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaMHActionPerformed

    private void btnXoaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMHActionPerformed
        String mamh = txtmamh.getText();
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa môn học này.", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            ArrayList<LopHocPhan> listLHP = new LopHocPhanDAO().deleteByMaMH(mamh);
            for (LopHocPhan lhp : listLHP) {
                new DangKyHocDAO().deleteByMaLHP(lhp.getMaLHP(), lhp.getHocky(), lhp.getNamhoc());
                Entities.LichThi lt = new Entities.LichThi(lhp.getMaLHP(), lhp.getHocky(), lhp.getNamhoc());
                new LichThiDAO().xoaLichthi(lt);
                new LopHocPhanDAO().xoaLHP(lhp);
            }
            boolean delete = new MonHocDAO().xoaMonhoc(mamh);
            if (delete) {
                JOptionPane.showMessageDialog(this, "Xóa môn học thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadQlmh();
                resetFormQlmh();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaMHActionPerformed

    private void btnLammoiMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiMHActionPerformed
        resetFormQlmh();
    }//GEN-LAST:event_btnLammoiMHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void resetFormQlmh() {
        txtmamh.setText("");
        txttenmh.setText("");
        txtsotc.setText("");
        cbmakhoa.setSelectedIndex(0);
        cbmamhtr.setSelectedIndex(0);

        txtmamh.setEnabled(true);
        btnThemMH.setEnabled(true);
        btnSuaMH.setEnabled(false);
        btnXoaMH.setEnabled(false);
    }

    public void loadComboBox() {
        listMH = new MonHocDAO().getAll();
        dcbmMaMH.addElement("");
        dcbmTenMH.addElement("");
        for (MonHoc mh : listMH) {
            dcbmMaMH.addElement(mh.getMaMH());
            dcbmTenMH.addElement(mh.getTenMH());

        }
        cbmamhtr.setModel(dcbmMaMH);
        cbtenmhtr.setModel(dcbmTenMH);

        listKhoa = new KhoaDAO().getAll();

        for (Khoa khoa : listKhoa) {
            dcbmMakhoa2.addElement(khoa.getMakhoa());
        }
        cbmakhoa.setModel(dcbmMakhoa2);

    }

    public void loadQlmh() {
        model.setRowCount(0);

        listMH = new MonHocDAO().getAll();
        int i = 1;
        for (MonHoc mh : listMH) {
            model.addRow(toObjectsDataMH(mh, i));

            i++;
        }
        bangdsmh.setModel(model);

    }

    public String mhTruoc(MonHoc mh) {
        ArrayList<MonHoc> list = new MonHocDAO().findMaMH_TRUOC(mh.getMaMH());
        String strmh = "";
        for (int i = 0; i < list.size(); i++) {
            strmh = strmh + list.get(i).getMaMH();
        }
        return strmh;
    }

    public Object[] toObjectsDataMH(MonHoc mh, int i) {

        Object[] ob = {i, mh.getMaMH(), mh.getTenMH(), mh.getSoTC(), mhTruoc(mh), mh.getMaKhoa()};
        return ob;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangdsmh;
    private javax.swing.JButton btnLammoiMH;
    private javax.swing.JButton btnSuaMH;
    private javax.swing.JButton btnThemMH;
    private javax.swing.JButton btnXoaMH;
    private javax.swing.JComboBox<String> cbmakhoa;
    private javax.swing.JComboBox<String> cbmamhtr;
    private javax.swing.JComboBox<String> cbtenmhtr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtmamh;
    private javax.swing.JTextField txtsotc;
    private javax.swing.JTextField txttenmh;
    // End of variables declaration//GEN-END:variables
}
