/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.KhoaDAO;
import DAO.LopDAO;
import DAO.PhuHuynhDAO;
import DAO.SinhVienDAO;
import Entities.Khoa;
import Entities.Lop;
import Entities.PhuHuynh;
import Entities.SinhVien;
import javax.swing.JOptionPane;

/**
 *
 * @author trung98
 */
public class ThongTinSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinSinhVien
     */
    public ThongTinSinhVien() {
        initComponents();
        loadThongtinSV();

    }

    public void loadThongtinSV() {

        SinhVien sv = new SinhVienDAO().findByMaSV(Main.nameLogin);

        Lop l = new LopDAO().findByMalop(sv.getMaLop());

        Khoa k = new KhoaDAO().findByMaKhoa(l.getMakhoa());

        PhuHuynh ph = new PhuHuynhDAO().findByMaSV(Main.nameLogin);

        // Set text sinh viên
        jtf_hoten.setText(sv.getHoTen());
        jtf_ngsinh.setText(sv.getNgSinh());
        jtf_sex.setText(sv.getGioitinh());
        jtf_addr.setText(sv.getNoisinh());
        jtf_phone.setText(sv.getSdt());
        jtf_masv.setText(Main.nameLogin);
        jtf_khoa.setText(k.getTenkhoa());

        // Set text phụ huynh
        tf_hotencha.setText(ph.getHotenCha());
        tf_hotenme.setText(ph.getHotenMe());
        tf_dclienhe.setText(ph.getDiachi());
        tf_sdtlienhe.setText(ph.getSodt());
        tf_quoctich.setText(ph.getQuoctich());

    }

    public void changeInfoPH() {
        String strnull = "";
        String hotencha = tf_hotencha.getText();
        String hotenme = tf_hotenme.getText();
        String diachi = tf_dclienhe.getText();
        String sdt = tf_sdtlienhe.getText();
        String quoctich = tf_quoctich.getText();

        if (hotencha.equals(strnull) || hotenme.equals(strnull) || diachi.equals(strnull) || sdt.equals(strnull) || quoctich.equals(strnull)) {
            JOptionPane.showMessageDialog(this, "Nội dung không được bỏ trống \n Xin vui lòng thử lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            PhuHuynh ph = new PhuHuynh(hotencha, hotenme, diachi, sdt, quoctich, Main.nameLogin);
            boolean update = new PhuHuynhDAO().updatePHByMaSV(ph);
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jtf_hoten = new javax.swing.JTextField();
        lb_hotencha1 = new javax.swing.JLabel();
        lb_hotenme1 = new javax.swing.JLabel();
        jtf_ngsinh = new javax.swing.JTextField();
        lb_dclienhe1 = new javax.swing.JLabel();
        jtf_sex = new javax.swing.JTextField();
        lb_sdtlienhe1 = new javax.swing.JLabel();
        jtf_addr = new javax.swing.JTextField();
        lb_quoctich1 = new javax.swing.JLabel();
        jtf_phone = new javax.swing.JTextField();
        lb_quoctich2 = new javax.swing.JLabel();
        jtf_masv = new javax.swing.JTextField();
        lb_quoctich3 = new javax.swing.JLabel();
        jtf_khoa = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lb_hotencha = new javax.swing.JLabel();
        tf_hotencha = new javax.swing.JTextField();
        lb_hotenme = new javax.swing.JLabel();
        tf_hotenme = new javax.swing.JTextField();
        lb_dclienhe = new javax.swing.JLabel();
        tf_dclienhe = new javax.swing.JTextField();
        lb_sdtlienhe = new javax.swing.JLabel();
        tf_sdtlienhe = new javax.swing.JTextField();
        lb_quoctich = new javax.swing.JLabel();
        tf_quoctich = new javax.swing.JTextField();
        btn_luu = new javax.swing.JButton();
        btn_xuat = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin sinh viên");

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel26.setText("*Lý lịch sinh viên");

        jtf_hoten.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_hoten.setEnabled(false);
        jtf_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_hotenActionPerformed(evt);
            }
        });

        lb_hotencha1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_hotencha1.setText("Họ và tên :");

        lb_hotenme1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_hotenme1.setText("Ngày, tháng, năm sinh :");

        jtf_ngsinh.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_ngsinh.setEnabled(false);

        lb_dclienhe1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_dclienhe1.setText("Giới tính :");

        jtf_sex.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_sex.setEnabled(false);
        jtf_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_sexActionPerformed(evt);
            }
        });

        lb_sdtlienhe1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_sdtlienhe1.setText("Địa chỉ :");

        jtf_addr.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_addr.setEnabled(false);

        lb_quoctich1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_quoctich1.setText("Số điện thoại :");

        jtf_phone.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_phone.setEnabled(false);

        lb_quoctich2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_quoctich2.setText("Mã số sinh viên :");

        jtf_masv.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_masv.setEnabled(false);

        lb_quoctich3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_quoctich3.setText("Khoa :");

        jtf_khoa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jtf_khoa.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_ngsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_dclienhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_hotenme1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_hotencha1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_quoctich3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_quoctich2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_quoctich1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_sdtlienhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hotencha1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_hotenme1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_ngsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_dclienhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_sdtlienhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_quoctich1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_quoctich2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_quoctich3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setText("*Thành phần gia đình");

        lb_hotencha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_hotencha.setText("Họ và tên cha :");

        tf_hotencha.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        lb_hotenme.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_hotenme.setText("Họ và tên mẹ :");

        tf_hotenme.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        lb_dclienhe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_dclienhe.setText("Địa chỉ liên hệ :");

        tf_dclienhe.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tf_dclienhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dclienheActionPerformed(evt);
            }
        });

        lb_sdtlienhe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_sdtlienhe.setText("Số điện thoại liên hệ :");

        tf_sdtlienhe.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        lb_quoctich.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lb_quoctich.setText("Quốc tịch :");

        tf_quoctich.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        btn_luu.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update_1.png"))); // NOI18N
        btn_luu.setText("Save");
        btn_luu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xuat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_xuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excel.png"))); // NOI18N
        btn_xuat.setText("Export");
        btn_xuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnback.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ba.png"))); // NOI18N
        btnback.setText("Back");
        btnback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_hotencha, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_hotenme, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_dclienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_sdtlienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_quoctich, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_quoctich, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_sdtlienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_hotencha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_hotenme, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_dclienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnback)
                .addGap(47, 47, 47))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hotencha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_hotencha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hotenme, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_hotenme, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_dclienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_dclienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_sdtlienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sdtlienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_quoctich, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_quoctich, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_hotenActionPerformed

    private void jtf_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_sexActionPerformed

    private void tf_dclienheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dclienheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dclienheActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        changeInfoPH();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_xuat;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JTextField jtf_addr;
    private javax.swing.JTextField jtf_hoten;
    private javax.swing.JTextField jtf_khoa;
    private javax.swing.JTextField jtf_masv;
    private javax.swing.JTextField jtf_ngsinh;
    private javax.swing.JTextField jtf_phone;
    private javax.swing.JTextField jtf_sex;
    private javax.swing.JLabel lb_dclienhe;
    private javax.swing.JLabel lb_dclienhe1;
    private javax.swing.JLabel lb_hotencha;
    private javax.swing.JLabel lb_hotencha1;
    private javax.swing.JLabel lb_hotenme;
    private javax.swing.JLabel lb_hotenme1;
    private javax.swing.JLabel lb_quoctich;
    private javax.swing.JLabel lb_quoctich1;
    private javax.swing.JLabel lb_quoctich2;
    private javax.swing.JLabel lb_quoctich3;
    private javax.swing.JLabel lb_sdtlienhe;
    private javax.swing.JLabel lb_sdtlienhe1;
    private javax.swing.JTextField tf_dclienhe;
    private javax.swing.JTextField tf_hotencha;
    private javax.swing.JTextField tf_hotenme;
    private javax.swing.JTextField tf_quoctich;
    private javax.swing.JTextField tf_sdtlienhe;
    // End of variables declaration//GEN-END:variables
}
